my:
    text: hello; **** This is Develop Enviroment *****
spring:
     datasource:
         url: jdbc:mysql://localhost:3306/mysql_maindb
         username: root
         password: 123456
         driverclassname: com.mysql.cj.jdbc.Driver
       jpa:
          hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL8Dialect
          show-sql: true
          properties:
             hibernate.format_sql: true
             hibernate.generate_statistics: true  
  
