my:
    text: hello abbas **** AUTO REFRESH10001 *****
datasource:
       url: jdbc:mysql://localhost:3306/my_database
       username: root
       password: 123456555555
       driverclassname: com.mysql.cj.jdbc.Driver
  
