my:
    text: hello abbas **** AUTO REFRESH10001 *****
spring:
     datasource:
         url: jdbc:mysql://localhost:3306/my_database
         username: root00
         password: 1234562
         driverclassname: com.mysql.cj.jdbc.Driver
  
