my:
  text: "hello; **** This is demo123 Develop Environment *****"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_maindb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
