my:
    text: hello; **** This is MSBaseInfoUsers Develop Enviroment *****
spring:   
     datasource:
         url: jdbc:mysql://localhost:3306/mysql_maindb
         username: root
         password: 123456
         driverclassname: com.mysql.cj.jdbc.Driver
      
  
